### ISSUE TITLE
compoundVariant tailwind intellisense regex issue

### ISSUE THREAD

**Issue by gamegee** [joe-bell/cva#181] opened 2023-07-11 07:15 UTC
**Describe the bug**
I am using the regex provided in the docs for tailwind intellisense autocomplete.

**To Reproduce**
I added this config to the `settings.json` of vscode

```tsx
"tailwindCSS.experimental.classRegex": [
  ["cva\\(([^)]*)\\)", "[\"'`]([^\"'`]*).*?[\"'`]"]
],
```
I have the following code:
```tsx
import { cva } from 'class-variance-authority'

const buttonCVA = cva(
  [
    'box-content flex items-center justify-center relative rounded-full font-semibold'
  ],
  {
    variants: {
      size: {
        xs: 'h-4 px-3 py-1.5 text-xs',
        s: 'h-5 px-4 py-2.5 text-xs',
        m: 'h-5 px-4 py-3 text-s',
        l: 'h-5 px-5 py-3.5 text-s',
        xl: 'h-5 px-6 py-4 text-m'
      },
      variant: {
        primary: '',
        secondary: '',
        tertiary: ''
      },
      intent: {
        default: '',
        error: ''
      },
      disabled: {
        true: 'pointer-events-none'
      }
    },
    compoundVariants: [
      {
        intent: 'default',
        variant: 'primary',
        class: `bg-brand-green-700 text-neutral-50
        hover:bg-brand-green-800
        active:bg-brand-green-900`
      },
      {
        intent: 'default',
        variant: 'primary',
        disabled: true,
        class: `bg-brand-green-700 text-neutral-50
        hover:bg-brand-green-800
        active:bg-brand-green-900`
      },
      {
        intent: 'default',
        variant: 'secondary',
        class: `bg-brand-green-50`
      }
    ]
  }
)
```

But for some reasons, the intellisense autocomplete doesn't work with the compound variants.
It seems related to the last item class
```tsx
{
        intent: 'default',
        variant: 'secondary',
        class: `bg-brand-green-50`
      }
```

**Expected behavior**
I expect intellisense to work.

**Screenshots**

**Desktop (please complete the following information):**

- OS: IOS
- Version: ^0.6.0

**Comment by joe-bell** [comment] 2023-07-11 10:42
Thanks! Going to mark this one as a duplicate of https://github.com/joe-bell/cva/discussions/85 — feel like this should be resolved holistically

**Closed by joe-bell** 2023-07-11 10:42 UTC
Labels: bug
