### ISSUE TITLE
Tailwind intellisense stops working based on size of cva object

### ISSUE THREAD

**Issue by LucasWinkler** [joe-bell/cva#77] opened 2022-12-06 04:33 UTC
**Describe the bug**
Not entirely sure if it's an issue with CVA, the regex or the extension for tailwind intellisense. Also this is my first issue so I'm sorry if I should be creating this elsewhere. 

I noticed when my compoundVariants had more than 7 objects inside the array the intellisense for tailwind completely stopped working. I created a new basic CVA button and noticed its not just compoundVariants it seems to depend on how long the strings are? If I duplicate intents, compoundVariants or any other object that has tailwind classes eventually the intellisense will no longer work. Also somethings the intellisense will work for some lines but not others. It all depends on how big component is. I feel like it's the regex but I'm not too sure.

**To Reproduce**

1. Create a basic CVA button
```
const button = cva(
  '',
  {
    variants: {
      intent: {
        primary: 'bg-green-600 hover:bg-green-700 text-white',
      },
      modifier: {
        something: 'rounded',
      },
    },
    compoundVariants: [
      {
        modifier: 'something',
        variant: 'primary',
        className: 'text-green-500 hover:bg-transparent hover:text-green-600',
      },
    ],
  }
);
```

3. Add/duplicate more intents or any other object that contains a few tailwind classes
4. Hover over tailwind class
5. See that there is no intellisense

**Expected behavior**
Intellisense should still show no matter how large the component is. 

**Screenshots**
How it should be:
![image](https://user-images.githubusercontent.com/43054519/205814929-166c75c0-e9be-41aa-9d5d-971753069fce.png)

After duplicating a few times:
![image](https://user-images.githubusercontent.com/43054519/205815163-4a6208d5-3ad5-4d3c-b8a4-a831f9ded377.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser N/A
- Version `tailwind@3.2.4, cva@0.3.0`

**Comment by joe-bell** [comment] 2022-12-06 07:41
Marking as a duplicate of #72

**Closed** 2022-12-06 07:42 UTC
Labels: bug
