### ISSUE TITLE
feature request multi dynamic styles

### ISSUE THREAD

**Issue by zakidze** [joe-bell/cva#222] opened 2023-09-17 10:12 UTC
hello 
i love CVA however it would be a great addition if you include 1 cva themes for component that have mutli parts example accordion

i want mutli thems of accordion including costum ons

the output would be somthing like this

![carbon (5)](https://github.com/joe-bell/cva/assets/61497110/5561c2f8-88ad-4331-b9f8-1941fe68a373)

**Comment by joe-bell** [comment] 2023-09-18 04:24
Duplicate of https://github.com/joe-bell/cva/discussions/94

**Closed by joe-bell** 2023-09-18 04:24 UTC
