### ISSUE TITLE
export `Config` type

### ISSUE THREAD

**Issue by ilovett** [joe-bell/cva#275] opened 2024-04-01 04:13 UTC
I'd like to be able to separate my config as `export const variantConfig: Config = { ... }` and then pull those into storybook stories `argTypes`, but I don't see how I can import that type. 

Alternatively, add `.config` to the returned function from `cva()` and we can access it through `variants.config`

```ts
argTypes: {
  color: {
    values: Object.keys(variants.config.variants.color),
    control: { type: 'radio' },
  }
}
```

**Comment by joe-bell** [comment] 2024-04-01 07:01
Duplicate of https://github.com/joe-bell/cva/discussions/146

**Closed by joe-bell** 2024-04-01 07:01 UTC
Labels: bug
