### ISSUE TITLE
suggestion: add slots API

### ISSUE THREAD

**Issue by erikshestopal** [joe-bell/cva#189] opened 2023-07-31 20:41 UTC
Just saw that [PandaCSS](https://github.com/chakra-ui/panda/pull/1132) is adding a "slots" API to handle compound components. Any interest in adding something like this to `cva` or is there support for this already and I missed it in the docs? 

Thanks!

**Comment by joe-bell** [comment] 2023-08-01 04:03
Duplicate of https://github.com/joe-bell/cva/discussions/94

**Closed by joe-bell** 2023-08-01 04:03 UTC
