### ISSUE TITLE
VariantProps not working in a component library

### ISSUE THREAD

**Issue by srijans38** [joe-bell/cva#190] opened 2023-08-09 15:03 UTC
**Describe the bug**
I am creating a component library for internal org use. For this I have a few components that use cva but when consuming these components in applications, the types from VariantProps are not reflected. Interestingly, the types work perfectly when consuming the component directly in storybook within the lib.

Here is a sample component:

```js

const button = cva(['some-styles'], {
  variants: {
    intent: {
      ....
    },
  }
});

interface ButtonProps
  extends VariantProps<typeof button>,
    React.ButtonHTMLAttributes<HTMLButtonElement> {
  text: string;
  icon?: React.ReactNode;
  iconPosition?: 'before' | 'after';
}

export function Button({
  text,
  className,
  intent,
  weight,
  icon,
  iconPosition = 'before',
  ...props
}: ButtonProps) {
    ....
}

```
And, here is the declaration file output by tsc:

```js
/// <reference types="react" />
import { VariantProps } from 'class-variance-authority';
declare const button: (props?: ({
    intent?: "primary" | "danger" | "outline" | null | undefined;
    weight?: "semibold" | "medium" | null | undefined;
} & import("class-variance-authority/dist/types").ClassProp) | undefined) => string;
interface ButtonProps extends VariantProps<typeof button>, React.ButtonHTMLAttributes<HTMLButtonElement> {
    text: string;
    icon?: React.ReactNode;
    iconPosition?: 'before' | 'after';
}
export declare function Button({ text, className, intent, weight, icon, iconPosition, ...props }: ButtonProps): import("react/jsx-runtime").JSX.Element;
export { };
```
What I suspect is happening here is that typescript is not taking the exports field for "./types" in package.json into account because manually editing the .d.ts file as below seems to work:

```js
declare const button: (props?: ({
    intent?: "primary" | "danger" | "outline" | null | undefined;
    weight?: "semibold" | "medium" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
```

So using `import("class-variance-authority/types").ClassProp` instead of `import("class-variance-authority/dist/types").ClassProp`

package.json: https://github.com/joe-bell/cva/blob/a1f7f504ef63f6f0b41a6a01218c19146337b46f/packages/class-variance-authority/package.json#L29-L31

Is there anything I can do to resolve this?

**Comment by joe-bell** [comment] 2023-08-09 17:28
Appreciate you taking the time to write this up, but I’m going to consider this as a duplicate of https://github.com/joe-bell/cva/discussions/143

Will make sure to tackle in `cva@1.0`

**Closed** 2023-08-09 17:28 UTC
Labels: bug
