### ISSUE TITLE
Variants always have additional implied types of `null` and `undefined`

### ISSUE THREAD

**Issue by pm0u** [joe-bell/cva#73] opened 2022-11-28 21:05 UTC
**Describe the bug**
When using CVA with typescript, any variants always have an additional implied type of `null` and `undefined` in addition to the options defined in the config object.

**To Reproduce**

1. Follow the example using typescript
2. Observe that the implied types for a given variant always include `null` and `undefined`

**Expected behavior**
The implied type for a given variant would be a tuple populated with the options defined for a given variant.

I'm unsure how to account for a situation where you would want to be able to accept null, but I also don't see a situation where this would actually be wanted?

**Screenshots**
<img width="651" alt="image" src="https://user-images.githubusercontent.com/410558/204380046-4682ed11-5cc8-4e26-9ca9-b6788f1293fe.png">

**Comment by pm0u** [comment] 2022-11-28 21:19
I am now seeing in the docs this note:
```
note: these default values can be removed completely by setting the variant as null
```

Which I take to be the reason a variant can accept `null`

However, I don't have any default variants defined for this example

**Comment by joe-bell** [comment] 2022-11-28 22:06
Thanks, but I'm closing as it's intended behaviour – `null` will always disable the variant entirely

cva's outputted types can always be omitted/[transformed](https://github.com/joe-bell/cva#required-variants) for advanced use-cases

**Closed by joe-bell** 2022-11-28 22:06 UTC
Labels: bug
